[[plugins]]                                    
repo = 'Shougo/dein.vim'                                          
# ------------------------------------                                    
# colorscheme lucius setting                                    
# ------------------------------------
[[plugins]]
repo = 'jonathanfilip/vim-lucius'
hook_add = '''  
set background=light
let s:high_contrast=1
'''

# [[plugins]]
# repo = 'tssm/fairyfloss.vim'
# hook_add = '''
#     colorscheme fairyfloss
# '''

# [[plugins]]
# repo = 'joshdick/onedark.vim'
# hook_add = '''
# if (has("autocmd") && !has("gui_running"))
#   augroup colorset
#     autocmd!
#     let s:white = { "gui": "#ABB2BF", "cterm": "145", "cterm16" : "7" }
#     autocmd ColorScheme * call onedark#set_highlight("Normal", { "fg": s:white }) " `bg` will not be styled since there is no `bg` setting
#   augroup END
# endif
# colorscheme onedark
# '''

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_powerline_fonts = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    nnoremap <silent><C-e> :NERDTreeToggle<CR>
    let g:NERDTreeWinSize = 25
    let g:neoterm_default_mod='belowright'
    let g:neoterm_size=10
    let g:neoterm_autoscroll=1
    '''

[[plugins]]
repo = 'kana/vim-fakeclip.git'


[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
nnoremap @p :T python %:t<CR>
nnoremap @h :T stack runghc %:t<CR>
nnoremap @c :T cargo run<CR>
nnoremap @l :T ptex2pdf -l -ot -kanji=utf8 %:t<CR> 
'''

# [[plugins]]
# repo = 'SirVer/ultisnips'
# hook_add = '''
# let g:UltiSnipsExpandTrigger="<c-j>"
# let g:UltiSnipsJumpForwardTrigger="<c-b>"
# let g:UltiSnipsJumpBackwardTrigger="<c-z>"
# '''

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
let g:netrw_browsex_viewer = 'open'
'''

[[plugins]]
repo = 'tpope/vim-rhubarb'

# [[plugins]]
# repo = 'junegunn/fzf'

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'miyakogi/seiya.vim'
hook_add = '''
let g:seiya_auto_enable=1
'''
